### ISSUE TITLE
Can't get value of input into render

### ISSUE THREAD

**Issue by mgseaton** [WSRogers98/Comp426Final#19]
So I have this in render: 
`let email = document.getElementById('email').value;`
but when I log into the console what this is getting, it's only getting an empty string, even though I've been typing in my email. Do y'all know why this might be 
It's getting the value of this input field: 
`<input type="text" placeholder="Enter Email" name="email" id="email" required>`

**Comment by WSRogers98** [comment]
<form class="form">
<textarea id="email" name="email" >email</textarea>
<textarea id="password" name="password" >password</textarea>
<button class="submit" type="submit">Submit</button>
</form>
 $root.on("submit",".form",Signup)

^written based off of how I did twitter. Signup would be the firebase call to signup we are given by somewhere in the firebase documentation. you can also do sign in through Google account I have that enabled (I've been told it is easier).  to get the email or password from a form like this it would be $("textarea[id=email]").val() and $("textarea[id=password]").val() respectively.  from your pull request, I can see you are on a late version of the master branch and that may cause some issues but idk for sure. I am not 100% positive on how to get jquery to work with firebase but the script at the top of the body should work (just changed the path for it to be from google api). hopefully, this helps a bit.
