### ISSUE TITLE
Login Submit Button 

### ISSUE THREAD

**Issue by mgseaton** [WSRogers98/Comp426Final#7]
So the login button in our index.html file has an id of 'loginSubmit'. Then, in Render.js, I have this: 

```
export const handleLogin = async function(e) {
    e.preventDefault(); 
    console.log('login submit'); 
}

$(async function() {
    $(document).on('click', '#loginSubmit', handleLogin); 
})
```

just trying to debug to see if the button's even doing what it should, but when i click it, nothing logs in the console. Does anyone see the problem

**Comment by mgseaton** [comment]
And I added `e.preventDefault()` as an attempt to stop the form from submitting and just getting something to log in the console but it doesn't seem to be doing that, so I'm missing something somewhere

**Comment by WSRogers98** [comment]
do you have a login that works that I can use? from what I see in the below image is what pops up. I think your login works and the request is fine but since there is no user with that login since we can't sign up. this wouldn't log anything to the console because it technically works but it won't work because there are no users yet. not sure if that's really why but that is what I think is happening.
<img width="958" alt="Screen Shot 2019-12-03 at 11 11 57 AM" src="https://user-images.githubusercontent.com/46759790/70068370-e13b8d00-15bd-11ea-9cc2-36822abe2ce3.png">

**Comment by mgseaton** [comment]
mmmm okay i'll create a login then!

**Comment by WSRogers98** [comment]
I may just be wrong because on the commit/pull  handle login is commented out so nothing would happen either way for me

**Comment by mgseaton** [comment]
ah yes i uncommented it in the code im working with now i'll do another commit soon

**Comment by mgseaton** [comment]
i'm going to paste my code below, does anyone see why it might still not be working 

`import axios from 'axios';

const root = new axios.create({
    baseURL: "http://localhost:3000"
});
  
export const handleLogin = async function(e) {
    e.preventDefault(); 
    console.log('login submit is working'); 
}

$(async function() {

    await root.post(`/account/create/`, {
        "name": "admin",
        "pass": "password",
    })
    
    $(document).on('click', '#loginSubmit', handleLogin); 

});`

**Comment by mgseaton** [comment]
i'm sad gorl

**Comment by WSRogers98** [comment]
I don't know the stuff with root but I know the Axios request should look something like this (mostly stolen from piazza)

const response = await axios({
                    method: 'POST',
                    url: 'http://localhost:3000/account/create',
                    data: {
                        "name": username,
                        "pass": password,
                        "data": {
                            "somedata": whatever data we need
                        }
                    }
                });
